### ISSUE TITLE
Add CodeMirror support

### ISSUE THREAD

**Issue by ildar-samit** [ildar-samit/learnix-preview#2]
All textareas that allow code editing should use [CodeMirror](https://codemirror.net/).

**Comment by Kimigabuchi** [comment]
Please test new features. Maybe we need something more.
https://github.com/ildar-samit/learnix-preview/commit/237dcc9bbcb69ef637658a62d2f98c08d4cc5b3a

**Comment by ildar-samit** [comment]
Can we use Javascript mode for now? Later we will change to Python.

Also, can you remove Codemirror from variable name field? It should be just a regular text field. Also see #7 (variable name should be used as is, not parsed). If possible, turn off autocomplete etc (so that it stops capitalizing first letter on iOS)

**Comment by Kimigabuchi** [comment]
> If possible, turn off autocomplete etc (so that it stops capitalizing first letter on iOS)

Is [this](https://github.com/sagemathinc/cocalc/issues/2092) the same problem?

**Comment by Kimigabuchi** [comment]
[Done](https://github.com/ildar-samit/learnix-preview/commit/95afbc7d45c30c28c45661150df1086dd0e23653)
1. Javascript mode instead of Python
2. Remove Codemirror from variable name field


Didn't yet:
1. Also see [#7](https://github.com/ildar-samit/learnix-preview/issues/7) (variable name should be used as is, not parsed)
2. If possible, turn off autocomplete etc (so that it stops capitalizing first letter on iOS)

**Comment by ildar-samit** [comment]
> Is this the same problem?

Opps, sorry. I meant turn off autocomplete for variable name field. *Not* CodeMirror! But I'm gonna close this issue for now, everything is already working great.
